@startuml
title Sequence Diagram for Member 4: Password Normalization (Template Method)
autonumber

participant "Spring:ApplicationRunner" as AR
participant "Concrete:KhachHangPasswordNormalizer" as KHN
participant "Abstract:AbstractPasswordNormalizer" as APN
participant "Repo:KhachHangRepository" as REPO
participant "Encoder:PasswordEncoder" as ENC

AR -> APN : run(args)
activate APN

APN -> KHN : findAll()
activate KHN
KHN -> REPO : findAll()
REPO --> KHN : list<Customer>
KHN --> APN : list
deactivate KHN

loop for each entity in list
    APN -> KHN : getPasswordHash(entity)
    activate KHN
    KHN --> APN : rawHash
    deactivate KHN
    
    APN -> APN : isBCrypt(rawHash)
    
    alt if not BCrypt
        APN -> ENC : encode(rawHash)
        ENC --> APN : newBCryptHash
        
        APN -> KHN : setPasswordHash(entity, newBCryptHash)
        activate KHN
        KHN --> APN : done
        deactivate KHN
        
        APN -> KHN : save(entity)
        activate KHN
        KHN -> REPO : save(entity)
        KHN --> APN : saved
        deactivate KHN
    end
end

APN --> AR : completed
deactivate APN

@enduml
